part of  "../app_widget/reactive_text_field.dart";
class FormGroupKey {
  FormGroupKey._();
  static const email = 'email';
  static const phone = 'phone';
  static const user = 'user';
  static const firstName = 'name';
  static const lastName = 'last name';
  static const gender = 'gender';
  static const birthday = 'birthday';
  static const newPassword = 'newPassword';
  static const submitNewPassword = 'submitNewPassword';
  static const oldPassword = 'oldPassword';
  static const password = 'password';
  static const search = 'search';
  static const city = 'city';
  static const playGround = 'play_ground';
  static const realStateType = 'real_state_type';
  static const swimmingPool = 'swimming_pool';
  static const storeHouse = 'store_house';
  static const section = 'section';
  static const rooms = 'rooms';
  static const garden = 'garden';
  static const country = 'country';
  static const floor = 'floor';
  static const street = 'street';
  static const locality = 'locality';
  static const postalCode = 'postalCode';
  static const code = 'code';
  static const note = 'note';
  static const addressName = 'addressName';
  static const apartmentNumber = 'apartment_number';
  static const buildingNumber = 'building_number';
  static const state = 'state';
  static const description = 'description';
  static const title = 'title';
  static const price = 'price';
  static const size = 'size';
  static const refund = 'refund';
    static const adType = 'adType';
    static const direction = 'direction';
    static const specification = 'specification';
}
